site_name: PSI Dashboard
repo_url: https://github.com/UNCG-DAISY/psi-dashboard

nav:
    - Home: index.md
    - Code of Conduct: code_of_conduct.md
    - Code Documentation: 
      - Overview: code_documentation/overview.md
    - User Documentation: 
      - Overview: user_documentation/overview.md
      # - Image: models/image.md
      # - TagData: models/tagData.md
      # - User: models/user.md

theme:
  name: 'material'
  custom_dir: 'theme'
  font:
    text: 'Ubuntu'
    code: 'Ubuntu Mono'
  palette:
    primary: 'light green'
    accent: 'orange'

# extra:
#   social:
#     - type: 'github'
#       link: ''    
  
# plugins:
#     - search
#     - git-revision-date

markdown_extensions:
  - pymdownx.superfences
  - admonition
  - pymdownx.details
  - pymdownx.mark
  - pymdownx.critic
  - pymdownx.tilde
  - codehilite:
      linenums: true
      guess_lang: False
      use_pygments: True
      #noclasses: True
      pygments_style: monokai
      

extra_css:
  - stylesheets/dark_theme.css
  - stylesheets/codehilite.css
  - stylesheets/custom.css
